export const locations = [
	'Alameda',
	'Alcaucín',
	'Alfarnate',
	'Alfarnatejo',
	'Algarrobo',
	'Algatocin',
	'Algorrobo Costa',
	'Alhaurín de la Torre',
	'Alhaurín el Grande',
	'Alhaurin Golf',
	'Almachar',
	'Almayate',
	'Almogía',
	'Almudena',
	'Aloha',
	'Alora',
	'Alozaina',
	'Alpandeire',
	'Altos de los Monteros',
	'Antequera',
	'Árchez',
	'Archidona',
	'Ardales',
	'Arenas',
	'Arriate',
	'Arroyo de la Miel',
	'Artola',
	'Atalaya',
	'Bahía de Marbella',
	'Bajondillo',
	'Bel Air',
	'Benadalid',
	'Benahavís',
	'Benajarafe',
	'Benalmadena',
	'Benalmadena Costa',
	'Benalmadena Pueblo',
	'Benamara',
	'Benamargosa',
	'Benamocarra',
	'Benaoján',
	'Benavista',
	'Cabopino',
	'Cajiz',
	'Cala del Moral',
	'Calahonda',
	'Calanova Golf',
	'Caleta de Vélez',
	'Calypso',
	'Campanillas',
	'Campillos',
	'Campo Mijas',
	'Cancelada',
	'Cañete la Real',
	'Canillas de Aceituno',
	'Canillas de Albaida',
	'Carib Playa',
	'Carranque',
	'Carratraca',
	'Cártama',
	'Carvajal',
	'Casabermeja',
	'Casarabonela',
	'Casares',
	'Casares Playa',
	'Casares Pueblo',
	'Centro Histórico',
	'Cerrado de Calderón',
	'Cerros del Aguila',
	'Chilches',
	'Churriana',
	'Ciudad Jardín',
	'Coín',
	'Colmenar',
	'Comares',
	'Cómpeta',
	'Cortes de la Frontera',
	'Cortijo Blanco',
	'Cortijo de Maza',
	'Costabella',
	'Costalita',
	'Cruz del Humilladero',
	'Cuevas De San Marcos',
	'Cuevas del Becerro',
	'Cútar',
	'Diana Park',
	'Doña Julia',
	'El Borge',
	'El Burgo',
	'El Chaparral',
	'El Chorro',
	'El Coto',
	'El Faro',
	'El Hornillo',
	'El Madroñal',
	'El Morche',
	'El Olivar',
	'El Padron',
	'El Palo',
	'El Paraiso',
	'El Pinillo',
	'El Presidente',
	'El Romeral',
	'El Rosario',
	'El Trapiche',
	'Elviria',
	'Entrerrios',
	'Estacion de Cartama',
	'Estepona',
	'Finca El Pato',
	'Frigiliana',
	'Fuengirola',
	'Fuente de Piedra',
	'Gaucín',
	'Genalguacil',
	'Gibralgalia',
	'Guadalmar',
	'Guadalmina Alta',
	'Guadalmina Baja',
	'Guaro',
	'Hacienda del Sol',
	'Hacienda Las Chapas',
	'Hacienda Paredes',
	'Humilladero',
	'Istán',
	'Iznate',
	'Jimera de Líbar',
	'Jubrique',
	'Júzcar',
	'La Atalaya',
	'La Azucarera',
	'La Barriguilla',
	'La Cala',
	'La Cala de Mijas',
	'La Cala Golf',
	'La Cala Hills',
	'La Campana',
	'La Capellania',
	'La Carihuela',
	'La Concha de Malaga',
	'La Duquesa',
	'La Heredia',
	'La Luz',
	'La Mairena',
	'La Quinta',
	'La Trinidad',
	'La Viñuela',
	'La Zagaleta',
	'Lagos',
	'Las Brisas',
	'Las Chapas',
	'Las Lagunas',
	'Las Zorrillas',
	'Lauro Golf',
	'Limonar',
	'Los Alamos',
	'Los Almendros',
	'Los Arqueros',
	'Los Boliches',
	'Los Flamingos',
	'Los Guindos',
	'Los Monteros',
	'Los Pacos',
	'Los Romanes',
	'Los Tilos',
	'Macharaviaya',
	'Mainake',
	'Málaga',
	'Málaga Centro',
	'Málaga Este',
	'Malagueta',
	'Mangas Verdes',
	'Manilva',
	'Marbella',
	'Marbesa',
	'Maro',
	'Mezquitilla',
	'Mijas',
	'Mijas Costa',
	'Mijas Golf',
	'Miraflores',
	'Moclinejo',
	'Mollina',
	'Monda',
	'Mondrón',
	'Monte Halcones',
	'Montefrío',
	'Montemar',
	'Nagüeles',
	'Nerja',
	'New Golden Mile',
	'Nueva Andalucía',
	'Ojén',
	'Parauta',
	'Pedregalejo',
	'Perchel Sur',
	'Periana',
	'Pinares de San Antón',
	'Pizarra',
	'Playamar',
	'Polígono Industrial Guadalhorce',
	'Polígonos',
	'Puente don Manuel',
	'Puerto Banús',
	'Puerto de Cabopino',
	'Puerto de la Torre',
	'Punta Chullera',
	'Recinto Ferial',
	'Reserva de Marbella',
	'Rincón de la Victoria',
	'Río Real',
	'Riogordo',
	'Riviera del Sol',
	'Ronda',
	'Salares',
	'San Luis de Sabinillas',
	'San Pedro de Alcántara',
	'Santa Clara',
	'Santa Cristina',
	'Santa Rosalía',
	'Sayalonga',
	'Sedella',
	'Selwo',
	'Sierra Blanca',
	'Sierrezuela',
	'Suárez',
	'Teatinos',
	'Teba',
	'The Golden Mile',
	'Tolox',
	'Torre de Benagalbón',
	'Torre del Mar',
	'Torre Real',
	'Torreblanca',
	'Torremar',
	'Torremolinos',
	'Torremolinos Centro',
	'Torremuelle',
	'Torrenueva',
	'Torrequebrada',
	'Torrox',
	'Torrox Costa',
	'Totalán',
	'Triana',
	'Valle de Abdalajis',
	'Valle del Sol',
	'Valle Romano',
	'Valle-Niza',
	'Valtocado',
	'Vélez-Málaga',
	'Villafranco del Guadalhorce',
	'Villanueva de Algaidas',
	'Villanueva De La Concepcion',
	'Villanueva de Tapia',
	'Villanueva del Rosario',
	'Villanueva del Trabuco',
	'Viñuela',
	'Yunquera',
	'Zalea'
];
